################################################################################
#
# libcurl
#
################################################################################

LIBCURL_VERSION = master
LIBCURL_SITE = $(call github,curl,curl,master)
LIBCURL_DEPENDENCIES = $(if $(BR2_PACKAGE_ZLIB),zlib) \
	$(if $(BR2_PACKAGE_RTMPDUMP),rtmpdump) \
	$(if $(BR2_PACKAGE_LIBPSL),libpsl) \
	wolfssl \
	zstd \
	nghttp2 \
	ngtcp2 \
	nghttp3 \
	libidn2

LIBCURL_INSTALL_STAGING = YES
LIBCURL_AUTORECONF = YES

LIBCURL_CONF_OPTS = \
	-DBUILD_CURL_EXE=ON \
	-DBUILD_SHARED_LIBS=ON \
	-DBUILD_STATIC_LIBS=OFF \
	-DBUILD_STATIC_CURL=OFF \
	-DCURL_LTO=ON \
	-DENABLE_DEBUG=OFF \
	-DCURL_DISABLE_SRP=ON \
	-DCURL_DISABLE_AWS=ON \
	-DCURL_DISABLE_DICT=ON \
	-DCURL_DISABLE_GOPHER=ON \
	-DCURL_DISABLE_IMAP=ON \
	-DCURL_DISABLE_LDAP=ON \
	-DCURL_DISABLE_LDAPS=ON \
	-DCURL_DISABLE_MQTT=ON \
	-DCURL_DISABLE_NETRC=ON \
	-DCURL_DISABLE_NTLM=ON \
	-DCURL_DISABLE_POP3=ON \
	-DCURL_DISABLE_PROXY=ON \
	-DCURL_DISABLE_RTSP=ON \
	-DCURL_DISABLE_SMB=ON \
	-DCURL_DISABLE_SMTP=ON \
	-DCURL_DISABLE_TELNET=ON \
	-DCURL_DISABLE_TFTP=ON \
	-DENABLE_IPV6=ON \
	-DBUILD_LIBCURL_DOCS=OFF \
	-DBUILD_MISC_DOCS=OFF \
	-DENABLE_CURL_MANUAL=OFF \
	-DCURL_ENABLE_SSL=ON \
	-DCURL_USE_WOLFSSL=ON \
	-DCURL_ZSTD=ON \
	-DCURL_BROTLI=OFF \
	-DUSE_NGHTTP2=ON \
	-DUSE_NGTCP2=ON \
	-DUSE_NGHTTP3=ON \
	-DUSE_LIBIDN2=ON \
	-DCURL_USE_LIBPSL=ON \
	-DCURL_USE_LIBSSH2=OFF \
	-DCURL_USE_LIBSSH=OFF

$(eval $(cmake-package))
