root = "/oci/buildkit"

[log]
  format = "text"

[dns]
  nameservers = ["1.1.1.1", "8.8.8.8"]
  options = ["edns0"]

[worker.oci]
  enabled = false

[worker.containerd]
  address = "/run/containerd/containerd.sock"
  enabled = true
  namespace = "buildkit"
  gc = true

  [worker.containerd.runtime]
    name = "io.containerd.runc.v2"
    options = { BinaryName = "runc" }
