#!/bin/bash

this=S12ipv6
. /lib/zebrafish/functions
assert_root $this

case $1 in
	start) ;;
	stop)  exit 0 ;;
	*)     fail "Usage: $this {start|stop}" ;;
esac

set -u
echo -n "Configuring network interfaces: "

mkdir -p /etc/network || exit 1

network_file="auto lo
iface lo inet loopback"

ipv6=$(get_kernel_parameter "ipv6")

if [[ -n "$ipv6" ]]; then
    ipv6_dns=$(get_kernel_parameter "ipv6dns")
    ipv6_netmask=$(get_kernel_parameter "ipv6netmask")
    ipv6_gateway=$(get_kernel_parameter "ipv6gateway")

    if [[ -z "$ipv6_netmask" ]]; then
        ipv6_netmask="64"
    fi

    if [[ -z "$ipv6_gateway" ]]; then
        ipv6_gateway="fe80::1"
    fi

    echo -n "IPv6 address $ipv6/$ipv6_netmask; gateway $ipv6_gateway; "

    if [[ -z "$ipv6_dns" ]]; then
        echo -n "nameservers Google; "
        ipv6_dns="2001:4860:4860::8888 2001:4860:4860::8844"
    else
        echo -n "nameservers $ipv6_dns; "
    fi

    network_file+="
auto eth0
iface eth0 inet6 static
address $ipv6
netmask $ipv6_netmask
dns-nameservers $ipv6_dns
gateway $ipv6_gateway"
else
    echo -n "No IPv6; "
fi

echo -e "$network_file" > /etc/network/interfaces || exit 2
echo "OK"
