#!/bin/bash

this=S12ip
. /lib/zebrafish/functions
assert_root $this

case $1 in
	start) ;;
	stop)  exit 0 ;;
	*)     fail "Usage: $this {start|stop}" ;;
esac

set -u
echo -n "Configuring network interfaces: "

mkdir -p /etc/network || exit 1

network_file="auto lo
iface lo inet loopback
"

# Use the new helpers to peek at each section's presence.
if zf_has_present ipv4.address; then
    network_file+="
auto eth0"
fi

if zf_has_present ipv4.address; then
    ipv4_address=$(zf_get ipv4.address)
    ipv4_broadcast=$(zf_get_default ipv4.broadcast "$ipv4_address")
    ipv4_subnet=$(zf_get_default ipv4.subnet "255.255.255.255")
    ipv4_gateway=$(zf_get_default ipv4.gateway "172.31.1.1")

    echo -n "IPv4 address $ipv4_address; subnet $ipv4_subnet; gateway $ipv4_gateway; "

    if zf_has_present ipv4.dns; then
        ipv4_dns=$(zebrafish-config --quiet list ipv4 --format shell)
        eval "$ipv4_dns"
        # After eval, $IPV4_DNS_COUNT and $IPV4_DNS_0, $IPV4_DNS_1, ...
        nameservers=""
        for ((i = 0; i < IPV4_DNS_COUNT; i++)); do
            v="IPV4_DNS_$i"
            if [ -z "$nameservers" ]; then
                nameservers="${!v}"
            else
                nameservers="$nameservers ${!v}"
            fi
        done
        echo -n "nameservers $nameservers; "
    else
        echo -n "nameservers Cloudflare; "
        nameservers="127.0.0.1"
    fi

    network_file+="
iface eth0 inet static
    address $ipv4_address
    broadcast $ipv4_broadcast
    netmask $ipv4_subnet
    gateway $ipv4_gateway
    pointopoint $ipv4_gateway
    dns-nameservers $nameservers"

    echo "OK"
else
    echo -n "No IPv4; "
fi

if zf_has_present ipv6.address; then
    ipv6_address=$(zf_get ipv6.address)
    ipv6_netmask=$(zf_get_default ipv6.netmask "64")
    ipv6_gateway=$(zf_get_default ipv6.gateway "fe80::1")

    echo -n "IPv6 address $ipv6_address/$ipv6_netmask; gateway $ipv6_gateway; "

    if zf_has_present ipv6.dns; then
        eval "$(zebrafish-config --quiet list ipv6 --format shell)"
        nameservers=""
        for ((i = 0; i < IPV6_DNS_COUNT; i++)); do
            v="IPV6_DNS_$i"
            if [ -z "$nameservers" ]; then
                nameservers="${!v}"
            else
                nameservers="$nameservers ${!v}"
            fi
        done
        echo -n "nameservers $nameservers; "
    else
        echo -n "nameservers Cloudflare; "
        nameservers="::1"
    fi

    network_file+="
iface eth0 inet6 static
    address $ipv6_address
    netmask $ipv6_netmask
    dns-nameservers $nameservers
    gateway $ipv6_gateway"
else
    echo -n "No IPv6; "
fi

echo -e "$network_file" > /etc/network/interfaces || exit 2
echo "OK"
