#!/bin/sh
#
# Start/stop dhcpcd
#

. /lib/zebrafish/functions

DAEMON=/sbin/dhcpcd
CONFIG=/etc/dhcpcd.conf
PIDFILE=/var/run/dhcpcd/pid

[ -f $CONFIG ] || exit 0

[ -L /var/db ] && [ ! -d "$(readlink -f /var/db)" ] \
	&& install -o root -g root -m 755 -d "$(readlink -f /var/db)" \
	|| install -o root -g root -m 755 -d /var/db

case "$1" in
  start)
	echo "Starting dhcpcd..."
	start-stop-daemon -S -x "$DAEMON" -p "$PIDFILE" -- -f "$CONFIG"
	sleep 0.25
	wait_for_internet
	;;
  stop)
	echo "Stopping dhcpcd..."
	start-stop-daemon -K -x "$DAEMON" -p "$PIDFILE" -o
	;;
  reload|force-reload)
	echo "Reloading dhcpcd configuration..."
	"$DAEMON" -s reload
	;;
  restart)
	"$0" stop
	sleep 1 # Prevent race condition: ensure dhcpcd stops before start.
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload|force-reload}"
	exit 1
esac
