#!/bin/sh

NAME=unbound
PIDFILE=/var/run/$NAME.pid
LOGFILE=/logs/system/$NAME.log

DAEMON_ARGS="-d -p"

[ -r "/etc/default/$NAME" ] && . "/etc/default/$NAME"

start() {
	echo -n "Starting $NAME: "
	start-stop-daemon --start --quiet --background \
		--make-pidfile --pidfile $PIDFILE \
		--startas /bin/sh -- -c "exec stdbuf -oL -eL $NAME $DAEMON_ARGS >> $LOGFILE 2>&1" \
		&& echo "OK" || echo "FAIL"
}

stop() {
	echo -n "Stopping $NAME: "
	start-stop-daemon --stop --quiet --pidfile $PIDFILE \
		&& echo "OK" || echo "FAIL"
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		# Restart, since there is no true "reload" feature.
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
