#!/bin/bash

this=S45nbd
. /lib/zebrafish/functions
assert_root $this

NAME_CLIENT=nbd-client
NAME_SERVER=nbd-server
PIDFILE_SERVER=/var/run/$NAME_SERVER.pid
LOGFILE_CLIENT=/logs/system/$NAME_CLIENT.log
LOGFILE_SERVER=/logs/system/$NAME_SERVER.log

# Persistent
ARGS_CLIENT="-p"

# No fork
ARGS_SERVER="-n"

do_start() {
  local client_count=0
  local server_count=0

  if zf_has_present nbd-client; then
    eval "$(zebrafish-config --quiet list nbd-client --format shell)"
    client_count=${NBD_CLIENT_COUNT:-0}
  fi

  if zf_has_present nbd-server; then
    eval "$(zebrafish-config --quiet list nbd-server --format shell)"
    server_count=${NBD_SERVER_COUNT:-0}
  fi

  if [[ "$client_count" -gt 0 ]]; then
    for ((i = 0; i < client_count; i++)); do
      local address="NBD_CLIENT_${i}_ADDRESS"
      local port="NBD_CLIENT_${i}_PORT"
      local disk="NBD_CLIENT_${i}_DEVICE"

      echo -n "Starting $NAME_CLIENT for ${!disk}: "
      stdbuf -oL -eL $NAME_CLIENT $ARGS_CLIENT "${!address}" "${!port}" "${!disk}" >> $LOGFILE_CLIENT 2>&1
    done

    # Wait for all disks to appear
    for ((i = 0; i < client_count; i++)); do
      local disk="NBD_CLIENT_${i}_DEVICE"

      local counter=0
      local max_attempts=10

      while [[ $counter -lt $max_attempts ]]; do
        if fdisk -l "${!disk}" >/dev/null 2>&1; then
          echo "${!disk} is available."
          break
        fi

        echo "Waiting for ${!disk}..."
        sleep 0.5
        ((counter++))
      done
    done
  fi

  if [[ "$server_count" -gt 0 ]]; then
    for ((i = 0; i < server_count; i++)); do
      local address="NBD_SERVER_${i}_ADDRESS"
      local disk="NBD_SERVER_${i}_DEVICE"

      echo -n "Starting $NAME_SERVER on ${!disk}: "
      start-stop-daemon --start --quiet --background \
        --make-pidfile --pidfile $PIDFILE_SERVER \
        --startas /bin/sh -- -c "exec stdbuf -oL -eL $NAME_SERVER $ARGS_SERVER ${!address} ${!disk} >> $LOGFILE_SERVER 2>&1" \
        && echo "OK" || echo "FAIL"
    done
  fi
}

do_stop() {
  if zf_has_present nbd-client; then
    eval "$(zebrafish-config --quiet list nbd-client --format shell)"
    local client_count=${NBD_CLIENT_COUNT:-0}
    for ((i = 0; i < client_count; i++)); do
      local disk="NBD_CLIENT_${i}_DEVICE"
      echo -n "Detaching ${!disk}: "
      nbd-client -d "${!disk}" && echo "OK" || echo "FAIL"
    done
  fi

  if zf_has_present nbd-server; then
    echo -n "Stopping $NAME_SERVER: "
    start-stop-daemon --stop --quiet --pidfile $PIDFILE_SERVER \
      && echo "OK" || echo "FAIL"
  fi
}

case "$1" in
  start)
    do_start
    ;;
  stop)
    do_stop
    ;;
  restart)
    do_stop
    sleep 1
    do_start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
