#!/bin/bash

this=S46mounts
. /lib/zebrafish/functions
assert_root $this

do_start() {
  local mount_count=0
  local key_count=0

  if zf_has_present zfs-mount; then
    eval "$(zebrafish-config --quiet list zfs-mount --format shell)"
    mount_count=${ZFS_MOUNT_COUNT:-0}
  fi

  if zf_has_present zfs-key; then
    eval "$(zebrafish-config --quiet list zfs-key --format shell)"
    key_count=${ZFS_KEY_COUNT:-0}
  fi

  if [[ "$mount_count" -gt 0 ]]; then
    for ((i = 0; i < mount_count; i++)); do
      local pool="ZFS_MOUNT_${i}_NAME"
      echo -n "Importing ZFS pool ${!pool}: "
      zpool import "${!pool}" && echo "OK" || echo "FAIL"
    done
  fi

  if [[ "$key_count" -gt 0 ]]; then
    for ((i = 0; i < key_count; i++)); do
      local dataset="ZFS_KEY_${i}_DATASET"
      local key="ZFS_KEY_${i}_KEY"

      echo -n "Importing ZFS key for ${!dataset}: "
      echo "${!key}" | zfs load-key -L prompt "${!dataset}" && echo "OK" || echo "FAIL"
    done
  fi

  for zfsmount in $(zfs list -H -o name,mountpoint | grep -v '^zebrafish' | grep -v 'none$' | cut -f 1); do
    echo -n "Mounting ZFS filesystem $zfsmount: "
    zfs mount "$zfsmount" && echo "OK" || echo "FAIL"
  done
}

do_stop() {
  for zfsmount in $(zfs list -H -o name,mountpoint | grep -v '^zebrafish' | grep -v 'none$' | cut -f 1); do
    echo -n "Unmounting ZFS filesystem $zfsmount: "
    zfs unmount "$zfsmount" && echo "OK" || echo "FAIL"
  done

  if zf_has_present zfs-mount; then
    eval "$(zebrafish-config --quiet list zfs-mount --format shell)"
    local mount_count=${ZFS_MOUNT_COUNT:-0}
    for ((i = 0; i < mount_count; i++)); do
      local pool="ZFS_MOUNT_${i}_NAME"
      echo -n "Detaching ZFS pool ${!pool}: "
      zpool export "${!pool}" && echo "OK" || echo "FAIL"
    done
  fi

  zfs unload-key -a
}

case "$1" in
  start)
    do_start
    ;;
  stop)
    do_stop
    ;;
  restart)
    do_stop
    sleep 1
    do_start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
