#!/bin/bash

this=S45ssh
. /lib/zebrafish/functions
assert_root $this

set -u

ssh_key=$(get_kernel_parameter "sshkey")

if [[ -n "$ssh_key" ]]; then
    user=signalizer
    ssh_folder=/home/$user/.ssh
    authorized_keys="$ssh_folder"/authorized_keys

    echo -n "Installing SSH key: "
    rm -f "$authorized_keys"
    mkdir -p "$ssh_folder" || exit 2
    echo -e "$ssh_key" > "$authorized_keys" || exit 3
    chown -R $user:$user "$ssh_folder" || exit 4
    echo "OK"
fi

mkdir -p /logs/system
echo "OK"