#!/bin/sh

. /lib/zebrafish/functions

NAME=containerd
DAEMON=/usr/bin/$NAME
PIDFILE=/var/run/$NAME.pid
LOGFILE=/logs/system/$NAME.log

[ -r /etc/default/$NAME ] && . /etc/default/$NAME $1

do_start() {
        # https://stackoverflow.com/a/21029952/2412477
        echo -n "Starting $NAME: "
        start-stop-daemon --start --quiet --background \
                --make-pidfile --pidfile $PIDFILE \
                --startas /bin/sh -- -c "exec stdbuf -oL -eL $DAEMON $DAEMON_ARGS >> $LOGFILE 2>&1" \
                && echo "OK" || echo "FAIL"
}

do_stop() {
        echo -n "Stopping $NAME: "
        start-stop-daemon --stop --quiet --pidfile $PIDFILE \
                && echo "OK" || echo "FAIL"
}

case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
                sleep 1
                do_start
                ;;
	*)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac
