#!/bin/sh
# devtmpfs does not get automounted for initramfs
mkdir -p /dev
/bin/mount -t devtmpfs devtmpfs /dev
exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console

echo "Continuing init..."
exec /sbin/init "$@"