version = 2
root = "/oci/containerd"

[plugins."io.containerd.grpc.v1.cri".containerd]
  snapshotter = "overlayfs"

[plugins."io.containerd.snapshotter.v1.zfs"]
  root = "/oci/containerd/io.containerd.snapshotter.v1.zfs"
